apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: build-deploy-wildwest-pipelinerun
spec:
  pipelineRef:
    name: build-and-deploy
  params:
  - name: deployment-name
    value: wildwest
  - name: git-url
    value: https://github.com/bstrauss84/wild-west-kubernetes.git
  - name: IMAGE
    value: image-registry.openshift-image-registry.svc:5000/$(context.pipelineRun.namespace)/wildwest
  workspaces:
  - name: shared-workspace
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 500Mi
