apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-and-deploy
spec:
  workspaces:
  - name: shared-workspace
  params:
  - name: deployment-name
    type: string
    description: name of the deployment to be patched
  - name: git-url
    type: string
    description: url of the git repo for the code of deployment
  - name: git-revision
    type: string
    description: revision to be used from repo of the code for deployment
    default: master
  - name: IMAGE
    type: string
    description: image to be build from the code
  tasks:
  - name: fetch-repository
    taskRef:
      name: git-clone
      kind: ClusterTask
    workspaces:
    - name: output
      workspace: shared-workspace
    params:
    - name: url
      value: $(params.git-url)
    - name: subdirectory
      value: ""
    - name: deleteExisting
      value: "true"
    - name: revision
      value: $(params.git-revision)
  - name: build-image
    taskRef:
      name: buildah
      kind: ClusterTask
    params:
    - name: IMAGE
      value: $(params.IMAGE)
    workspaces:
    - name: source
      workspace: shared-workspace
    runAfter:
    - fetch-repository
  - name: image-scan
    params:
    - name: image
      value: $(params.IMAGE)
    - name: rox_api_token
      value: roxsecrets
    - name: rox_central_endpoint
      value: roxsecrets
    - name: output_format
      value: table
    - name: image_digest
      value: $(tasks.build-image.results.IMAGE_DIGEST)
    runAfter:
    - build-image
    taskRef:
      kind: ClusterTask
      name: rox-image-scan
  - name: image-check
    params:
    - name: image
      value: $(params.IMAGE)
    - name: rox_api_token
      value: roxsecrets
    - name: rox_central_endpoint
      value: roxsecrets
    - name: image_digest
      value: $(tasks.build-image.results.IMAGE_DIGEST)
    runAfter:
      - build-image
    taskRef:
      kind: ClusterTask
      name: rox-image-check
  - name: deploy-check
    params:
    - name: GIT_REPOSITORY
      value: $(params.git-url)
    - name: rox_api_token
      value: roxsecrets
    - name: rox_central_endpoint
      value: roxsecrets
    - name: file
      value: deployment.yaml
    - name: deployment_files_path
      value: kubernetes
    runAfter:
    - build-image
    taskRef:
      kind: ClusterTask
      name: rox-deployment-check
    workspaces:
    - name: source
      workspace: shared-workspace
  - name: apply-manifests
    taskRef:
      name: apply-manifests
    workspaces:
    - name: source
      workspace: shared-workspace
    runAfter:
    - image-check
    - image-scan
    - deploy-check
  - name: update-deployment
    taskRef:
      name: update-deployment
    params:
    - name: deployment
      value: $(params.deployment-name)
    - name: IMAGE
      value: $(params.IMAGE)
    runAfter:
    - apply-manifests
